/// <reference types="vitest/config" />
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  base: './',
  build: {
    outDir: 'dist',
    // Disabled for hosted builds — avoids publishing key-handling logic via .map files.
    sourcemap: false,
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./tests/setup.ts'],
    include: ['tests/**/*.test.ts', 'tests/**/*.test.tsx'],
    coverage: {
      provider: 'v8',
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/main.tsx',
        'src/**/*.css',
        'src/components/edges/**',
        'src/components/nodes/AgentNode.tsx',
        'src/components/nodes/ChatNode.tsx',
        'src/components/nodes/ToolNode.tsx',
        'src/components/nodes/NodeActionBar.tsx',
        'src/components/canvas/FlowCanvas.tsx',
        'src/components/canvas/CanvasHintBar.tsx',
        'src/components/header/Header.tsx',
        'src/components/sidebar/NodePalette.tsx',
        'src/components/sidebar/PaletteAccordionSection.tsx',
        'src/components/inspector/NodeInspector.tsx',
        'src/components/inspector/EdgeInspector.tsx',
        'src/components/inspector/ToolInspectorFields.tsx',
        'src/components/inspector/ToolSafetyNotice.tsx',
        'src/components/inspector/InspectorSetupNotice.tsx',
        'src/components/inspector/BaseInspectorShell.tsx',
        'src/components/inspector/PortLegend.tsx',
        'src/components/nodes/PortHandles.tsx',
        'src/components/settings/SettingsPanel.tsx',
        'src/components/settings/CloudPrivacyGuide.tsx',
        'src/components/settings/ModelLoadBanner.tsx',
        'src/components/debugger/DebugTerminal.tsx',
        'src/components/onboarding/WelcomeBanner.tsx',
        'src/components/dialog/ConfirmDialog.tsx',
        'src/stores/connectionStore.ts',
        'src/components/tutorial/**',
        'src/components/guide/**',
        'src/App.tsx',
        // Integration-boundary tools that cannot execute under jsdom:
        // canvas 2D rendering (no node-canvas), WebAudio (no audio hardware),
        // and CDN/WASM dynamic imports (network + foreign runtimes).
        // Their pure-logic siblings ARE covered — see tests/tools/pure-logic-*.test.ts
        // and tests/tools/network-tools.test.ts.
        'src/tools/imageEdit.ts',
        'src/tools/thumbnailGen.ts',
        'src/tools/carouselGen.ts',
        'src/tools/imageToFile.ts',
        'src/tools/audioTool.ts',
        'src/tools/webAudioTool.ts',
        'src/tools/audioWorkletTool.ts',
        'src/tools/pythonRunner.ts',
        'src/tools/wasmRunner.ts',
        'src/tools/rustLib.ts',
        'src/tools/tfjsTool.ts',
        'src/tools/d3Chart.ts',
        'src/tools/chartJsTool.ts',
        'src/tools/photonTool.ts',
        'src/tools/pdfTool.ts',
        'src/tools/markdownToHtml.ts',
        'src/tools/ffprobeTool.ts',
        'src/tools/barcodeGen.ts',
        'src/tools/ocrTool.ts',
        'src/tools/languageDetect.ts',
        'src/tools/spellCheck.ts',
        'src/tools/textDiff.ts',
        'src/tools/yamlTool.ts',
        'src/tools/diffusionStudioTool.ts',
        'src/tools/terminal.ts',
        'src/tools/mathLatex.ts',
        'src/tools/mermaidRenderer.ts',
      ],
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 70,
        statements: 70,
      },
    },
  },
})
