import type { TutorialStep } from '../tutorialSteps'

export const PIPELINE_QUEST_STEPS: TutorialStep[] = [
  {
    id: 'pipeline-briefing',
    title: 'Pipeline Briefing',
    body: 'Time to level up. You will chain **JSON Tool** and **Custom Script** between Chat and Agent — parse structured data, reshape it in a sandbox, then let the AI explain. Still free. Still no server.',
    placement: 'center',
    advance: 'manual',
  },
  {
    id: 'pipeline-mission',
    title: 'Fresh Canvas',
    body: 'Same rules as before: blocks on the canvas, lines between them, data flows left to right. This time the middle steps are pure browser tools.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'manual',
  },
  {
    id: 'pipeline-drag-chat',
    title: 'Start with Chat',
    body: 'Drag **Chat** onto the canvas. You will paste JSON here in a minute.',
    target: 'palette-chat',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['chat'],
  },
  {
    id: 'pipeline-drag-json',
    title: 'Add JSON Tool',
    body: 'Search **JSON Tool** in the palette (Essentials group) and drag it on. It pretty-prints JSON text from Chat.',
    target: 'palette-json-tool',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-json-tool'],
  },
  {
    id: 'pipeline-drag-script',
    title: 'Add Custom Script',
    body: 'Drag **Custom Script** from the Custom group. You will write a tiny snippet that extracts a field from the JSON.',
    target: 'palette-custom-script',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['tool-custom-script'],
  },
  {
    id: 'pipeline-drag-agent',
    title: 'Add an Agent',
    body: 'Drag an **Agent** to read the script output and answer in plain English.',
    target: 'palette-agent',
    placement: 'right',
    advance: 'auto',
    highlightPalette: ['agent'],
  },
  {
    id: 'pipeline-ports-lesson',
    title: 'Typed Ports',
    body: 'Each block has colored **ports** — text, JSON, and more. Try dragging from Chat **Message** to Agent **Out** (wrong direction/types) — incompatible ports dim red and the Activity log explains why. Then wire **Message → In** on each tool in order (or skip ahead if you already wired correctly).',
    target: 'canvas',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'pipeline-wire',
    title: 'Wire the Pipeline',
    body: 'Connect **Chat → JSON Tool → Custom Script → Agent** using **Message**, **In**, **Out**, and **Context** ports. Four blocks, three lines — no shortcuts.',
    target: 'canvas',
    placement: 'bottom',
    advance: 'auto',
  },
  {
    id: 'pipeline-script',
    title: 'Write the Script',
    body: 'Click the **Custom Script** node. In the inspector, paste this script:\n\n`return helpers.jsonParse(input).snack`\n\nThen click **Run test** if you like — it runs locally in a sandbox.',
    target: 'inspector-custom-script',
    placement: 'left',
    advance: 'auto',
  },
  {
    id: 'pipeline-drop-json',
    title: 'Paste Sample JSON',
    body: 'In Chat, paste: `{"snack":"pizza","rating":9}` — the JSON Tool will format it, the script will pull out `pizza`, and the agent will react.',
    target: 'chat-input',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'pipeline-launch',
    title: 'Run the Pipeline',
    body: 'Press **send**. Watch the Activity log — each tool runs in order before the agent speaks.',
    target: 'chat-send',
    placement: 'top',
    advance: 'auto',
  },
  {
    id: 'pipeline-epilogue',
    title: 'Pipeline Online',
    body: "You chained browser tools with a sandbox script — that is real workflow engineering. Try **Encoding Chain**, **Writer's room**, or **Capture desk** next, explore the palette sidebar, or read the **Guide**.",
    placement: 'center',
    advance: 'manual',
  },
]
